import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'es' | 'de' | 'pl' | 'fr' | 'it' | 'pt' | 'ru';

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'Volume Calculator',
    'app.subtitle': 'Professional Construction Volume & Material Estimation',
    'topbar.language': 'Language',
    'topbar.settings': 'Settings',
    'topbar.export': 'Export',
    'layer.addLayer': 'Add Layer',
    'layer.title': 'Layers',
    'layer.name': 'Layer Name',
    'layer.thickness': 'Thickness (cm)',
    'layer.material': 'Material',
    'layer.remove': 'Remove',
    'layer.unit': 'm',
    'dimensions.length': 'Length',
    'dimensions.width': 'Width',
    'dimensions.height': 'Height',
    'dimensions.lengthUnit': 'm',
    'dimensions.widthUnit': 'm',
    'dimensions.heightUnit': 'm',
    'results.area': 'Total Area',
    'results.volume': 'Total Volume',
    'results.linearMeters': 'Linear Meters',
    'results.m2': 'm²',
    'results.m3': 'm³',
    'results.m': 'm',
    'results.summary': 'Results Summary',
    'results.noData': 'No calculations yet. Add elements to get started.',
    'material.name': 'Material Name',
    'material.pricePerUnit': 'Price per Unit',
    'material.unit': 'Unit (m², m³, m)',
    'material.totalCost': 'Total Cost',
    'material.addMaterial': 'Add Material',
    'material.summary': 'Material Price Summary',
    'element.name': 'Element Name',
    'element.dimensions': 'Dimensions',
    'element.quantity': 'Qty',
    'element.type': 'Type',
    'element.breakdownTable': 'Element Breakdown',
    'element.noElements': 'No elements added yet.',
    'export.title': 'Export Data',
    'export.csv': 'Export as CSV',
    'export.excel': 'Export as Excel',
    'export.pdf': 'Export as PDF',
    'export.cancel': 'Cancel',
    'export.download': 'Download',
    'actions.calculate': 'Calculate',
    'actions.reset': 'Reset',
    'actions.clear': 'Clear All',
    'actions.add': 'Add',
    'actions.delete': 'Delete',
    'actions.edit': 'Edit',
    'actions.save': 'Save',
    'actions.cancel': 'Cancel',
    'validation.required': 'This field is required',
    'validation.invalidNumber': 'Please enter a valid number',
    'validation.positiveNumber': 'Please enter a positive number',
    'validation.invalidDimensions': 'Invalid dimensions provided',
  },
  es: {
    'app.title': 'Calculadora de Volumen',
    'app.subtitle': 'Estimación Profesional de Volumen y Materiales de Construcción',
    'topbar.language': 'Idioma',
    'topbar.settings': 'Configuración',
    'topbar.export': 'Exportar',
    'layer.addLayer': 'Agregar Capa',
    'layer.title': 'Capas',
    'layer.name': 'Nombre de la Capa',
    'layer.thickness': 'Espesor (cm)',
    'layer.material': 'Material',
    'layer.remove': 'Eliminar',
    'layer.unit': 'm',
    'dimensions.length': 'Largo',
    'dimensions.width': 'Ancho',
    'dimensions.height': 'Alto',
    'dimensions.lengthUnit': 'm',
    'dimensions.widthUnit': 'm',
    'dimensions.heightUnit': 'm',
    'results.area': 'Área Total',
    'results.volume': 'Volumen Total',
    'results.linearMeters': 'Metros Lineales',
    'results.m2': 'm²',
    'results.m3': 'm³',
    'results.m': 'm',
    'results.summary': 'Resumen de Resultados',
    'results.noData': 'Sin cálculos aún. Agregue elementos para comenzar.',
    'material.name': 'Nombre del Material',
    'material.pricePerUnit': 'Precio por Unidad',
    'material.unit': 'Unidad (m², m³, m)',
    'material.totalCost': 'Costo Total',
    'material.addMaterial': 'Agregar Material',
    'material.summary': 'Resumen de Precios de Materiales',
    'element.name': 'Nombre del Elemento',
    'element.dimensions': 'Dimensiones',
    'element.quantity': 'Cant.',
    'element.type': 'Tipo',
    'element.breakdownTable': 'Desglose de Elementos',
    'element.noElements': 'Sin elementos agregados aún.',
    'export.title': 'Exportar Datos',
    'export.csv': 'Exportar como CSV',
    'export.excel': 'Exportar como Excel',
    'export.pdf': 'Exportar como PDF',
    'export.cancel': 'Cancelar',
    'export.download': 'Descargar',
    'actions.calculate': 'Calcular',
    'actions.reset': 'Reiniciar',
    'actions.clear': 'Borrar Todo',
    'actions.add': 'Agregar',
    'actions.delete': 'Eliminar',
    'actions.edit': 'Editar',
    'actions.save': 'Guardar',
    'actions.cancel': 'Cancelar',
    'validation.required': 'Este campo es obligatorio',
    'validation.invalidNumber': 'Por favor ingrese un número válido',
    'validation.positiveNumber': 'Por favor ingrese un número positivo',
    'validation.invalidDimensions': 'Dimensiones inválidas proporcionadas',
  },
  de: {
    'app.title': 'Volumenrechner',
    'app.subtitle': 'Professionelle Schätzung von Baustoffvolumen und Materialien',
    'topbar.language': 'Sprache',
    'topbar.settings': 'Einstellungen',
    'topbar.export': 'Exportieren',
    'layer.addLayer': 'Schicht Hinzufügen',
    'layer.title': 'Schichten',
    'layer.name': 'Schichtname',
    'layer.thickness': 'Dicke (cm)',
    'layer.material': 'Material',
    'layer.remove': 'Entfernen',
    'layer.unit': 'm',
    'dimensions.length': 'Länge',
    'dimensions.width': 'Breite',
    'dimensions.height': 'Höhe',
    'dimensions.lengthUnit': 'm',
    'dimensions.widthUnit': 'm',
    'dimensions.heightUnit': 'm',
    'results.area': 'Gesamtfläche',
    'results.volume': 'Gesamtvolumen',
    'results.linearMeters': 'Laufmeter',
    'results.m2': 'm²',
    'results.m3': 'm³',
    'results.m': 'm',
    'results.summary': 'Ergebniszusammenfassung',
    'results.noData': 'Noch keine Berechnungen. Elemente hinzufügen zum Starten.',
    'material.name': 'Materialname',
    'material.pricePerUnit': 'Preis pro Einheit',
    'material.unit': 'Einheit (m², m³, m)',
    'material.totalCost': 'Gesamtkosten',
    'material.addMaterial': 'Material Hinzufügen',
    'material.summary': 'Materialpreisübersicht',
    'element.name': 'Elementname',
    'element.dimensions': 'Abmessungen',
    'element.quantity': 'Menge',
    'element.type': 'Typ',
    'element.breakdownTable': 'Elementaufschlüsselung',
    'element.noElements': 'Noch keine Elemente hinzugefügt.',
    'export.title': 'Daten Exportieren',
    'export.csv': 'Als CSV Exportieren',
    'export.excel': 'Als Excel Exportieren',
    'export.pdf': 'Als PDF Exportieren',
    'export.cancel': 'Abbrechen',
    'export.download': 'Herunterladen',
    'actions.calculate': 'Berechnen',
    'actions.reset': 'Zurücksetzen',
    'actions.clear': 'Alles Löschen',
    'actions.add': 'Hinzufügen',
    'actions.delete': 'Löschen',
    'actions.edit': 'Bearbeiten',
    'actions.save': 'Speichern',
    'actions.cancel': 'Abbrechen',
    'validation.required': 'Dieses Feld ist erforderlich',
    'validation.invalidNumber': 'Bitte geben Sie eine gültige Zahl ein',
    'validation.positiveNumber': 'Bitte geben Sie eine positive Zahl ein',
    'validation.invalidDimensions': 'Ungültige Abmessungen angegeben',
  },
  pl: {
    'app.title': 'Kalkulator Objętości',
    'app.subtitle': 'Profesjonalna Estymacja Objętości i Materiałów Budowlanych',
    'topbar.language': 'Język',
    'topbar.settings': 'Ustawienia',
    'topbar.export': 'Eksportuj',
    'layer.addLayer': 'Dodaj Warstwę',
    'layer.title': 'Warstwy',
    'layer.name': 'Nazwa Warstwy',
    'layer.thickness': 'Grubość (cm)',
    'layer.material': 'Materiał',
    'layer.remove': 'Usuń',
    'layer.unit': 'm',
    'dimensions.length': 'Długość',
    'dimensions.width': 'Szerokość',
    'dimensions.height': 'Wysokość',
    'dimensions.lengthUnit': 'm',
    'dimensions.widthUnit': 'm',
    'dimensions.heightUnit': 'm',
    'results.area': 'Całkowita Powierzchnia',
    'results.volume': 'Całkowita Objętość',
    'results.linearMeters': 'Metry Bieżące',
    'results.m2': 'm²',
    'results.m3': 'm³',
    'results.m': 'm',
    'results.summary': 'Streszczenie Wyników',
    'results.noData': 'Brak obliczeń. Dodaj elementy aby rozpocząć.',
    'material.name': 'Nazwa Materiału',
    'material.pricePerUnit': 'Cena za Jednostkę',
    'material.unit': 'Jednostka (m², m³, m)',
    'material.totalCost': 'Całkowity Koszt',
    'material.addMaterial': 'Dodaj Materiał',
    'material.summary': 'Podsumowanie Cen Materiałów',
    'element.name': 'Nazwa Elementu',
    'element.dimensions': 'Wymiary',
    'element.quantity': 'Ilość',
    'element.type': 'Typ',
    'element.breakdownTable': 'Podział Elementów',
    'element.noElements': 'Brak dodanych elementów.',
    'export.title': 'Eksportuj Dane',
    'export.csv': 'Eksportuj jako CSV',
    'export.excel': 'Eksportuj jako Excel',
    'export.pdf': 'Eksportuj jako PDF',
    'export.cancel': 'Anuluj',
    'export.download': 'Pobierz',
    'actions.calculate': 'Oblicz',
    'actions.reset': 'Resetuj',
    'actions.clear': 'Wyczyść Wszystko',
    'actions.add': 'Dodaj',
    'actions.delete': 'Usuń',
    'actions.edit': 'Edytuj',
    'actions.save': 'Zapisz',
    'actions.cancel': 'Anuluj',
    'validation.required': 'To pole jest wymagane',
    'validation.invalidNumber': 'Proszę wpisać prawidłową liczbę',
    'validation.positiveNumber': 'Proszę wpisać liczbę dodatnią',
    'validation.invalidDimensions': 'Podane wymiary są nieprawidłowe',
  },
  fr: {
    'app.title': 'Calculatrice de Volume',
    'app.subtitle': 'Estimation Professionnelle du Volume et des Matériaux de Construction',
    'topbar.language': 'Langue',
    'topbar.settings': 'Paramètres',
    'topbar.export': 'Exporter',
    'layer.addLayer': 'Ajouter une Couche',
    'layer.title': 'Couches',
    'layer.name': 'Nom de la Couche',
    'layer.thickness': 'Épaisseur (cm)',
    'layer.material': 'Matériau',
    'layer.remove': 'Supprimer',
    'layer.unit': 'm',
    'dimensions.length': 'Longueur',
    'dimensions.width': 'Largeur',
    'dimensions.height': 'Hauteur',
    'dimensions.lengthUnit': 'm',
    'dimensions.widthUnit': 'm',
    'dimensions.heightUnit': 'm',
    'results.area': 'Superficie Totale',
    'results.volume': 'Volume Total',
    'results.linearMeters': 'Mètres Linéaires',
    'results.m2': 'm²',
    'results.m3': 'm³',
    'results.m': 'm',
    'results.summary': 'Résumé des Résultats',
    'results.noData': 'Aucun calcul pour le moment. Ajoutez des éléments pour commencer.',
    'material.name': 'Nom du Matériau',
    'material.pricePerUnit': 'Prix par Unité',
    'material.unit': 'Unité (m², m³, m)',
    'material.totalCost': 'Coût Total',
    'material.addMaterial': 'Ajouter un Matériau',
    'material.summary': 'Résumé des Prix des Matériaux',
    'element.name': 'Nom de l\'Élément',
    'element.dimensions': 'Dimensions',
    'element.quantity': 'Quantité',
    'element.type': 'Type',
    'element.breakdownTable': 'Ventilation des Éléments',
    'element.noElements': 'Aucun élément ajouté pour le moment.',
    'export.title': 'Exporter les Données',
    'export.csv': 'Exporter en CSV',
    'export.excel': 'Exporter en Excel',
    'export.pdf': 'Exporter en PDF',
    'export.cancel': 'Annuler',
    'export.download': 'Télécharger',
    'actions.calculate': 'Calculer',
    'actions.reset': 'Réinitialiser',
    'actions.clear': 'Tout Effacer',
    'actions.add': 'Ajouter',
    'actions.delete': 'Supprimer',
    'actions.edit': 'Modifier',
    'actions.save': 'Enregistrer',
    'actions.cancel': 'Annuler',
    'validation.required': 'Ce champ est obligatoire',
    'validation.invalidNumber': 'Veuillez entrer un nombre valide',
    'validation.positiveNumber': 'Veuillez entrer un nombre positif',
    'validation.invalidDimensions': 'Dimensions invalides fournies',
  },
  it: {
    'app.title': 'Calcolatore di Volume',
    'app.subtitle': 'Stima Professionale del Volume e dei Materiali Edili',
    'topbar.language': 'Lingua',
    'topbar.settings': 'Impostazioni',
    'topbar.export': 'Esporta',
    'layer.addLayer': 'Aggiungi Strato',
    'layer.title': 'Strati',
    'layer.name': 'Nome Strato',
    'layer.thickness': 'Spessore (cm)',
    'layer.material': 'Materiale',
    'layer.remove': 'Rimuovi',
    'layer.unit': 'm',
    'dimensions.length': 'Lunghezza',
    'dimensions.width': 'Larghezza',
    'dimensions.height': 'Altezza',
    'dimensions.lengthUnit': 'm',
    'dimensions.widthUnit': 'm',
    'dimensions.heightUnit': 'm',
    'results.area': 'Area Totale',
    'results.volume': 'Volume Totale',
    'results.linearMeters': 'Metri Lineari',
    'results.m2': 'm²',
    'results.m3': 'm³',
    'results.m': 'm',
    'results.summary': 'Riepilogo dei Risultati',
    'results.noData': 'Nessun calcolo per il momento. Aggiungere elementi per iniziare.',
    'material.name': 'Nome Materiale',
    'material.pricePerUnit': 'Prezzo per Unità',
    'material.unit': 'Unità (m², m³, m)',
    'material.totalCost': 'Costo Totale',
    'material.addMaterial': 'Aggiungi Materiale',
    'material.summary': 'Riepilogo Prezzi Materiali',
    'element.name': 'Nome Elemento',
    'element.dimensions': 'Dimensioni',
    'element.quantity': 'Qtà',
    'element.type': 'Tipo',
    'element.breakdownTable': 'Dettaglio Elementi',
    'element.noElements': 'Nessun elemento aggiunto per il momento.',
    'export.title': 'Esporta Dati',
    'export.csv': 'Esporta come CSV',
    'export.excel': 'Esporta come Excel',
    'export.pdf': 'Esporta come PDF',
    'export.cancel': 'Annulla',
    'export.download': 'Scarica',
    'actions.calculate': 'Calcola',
    'actions.reset': 'Ripristina',
    'actions.clear': 'Cancella Tutto',
    'actions.add': 'Aggiungi',
    'actions.delete': 'Rimuovi',
    'actions.edit': 'Modifica',
    'actions.save': 'Salva',
    'actions.cancel': 'Annulla',
    'validation.required': 'Questo campo è obbligatorio',
    'validation.invalidNumber': 'Inserisci un numero valido',
    'validation.positiveNumber': 'Inserisci un numero positivo',
    'validation.invalidDimensions': 'Dimensioni non valide fornite',
  },
  pt: {
    'app.title': 'Calculadora de Volume',
    'app.subtitle': 'Estimação Profissional de Volume e Materiais de Construção',
    'topbar.language': 'Idioma',
    'topbar.settings': 'Configurações',
    'topbar.export': 'Exportar',
    'layer.addLayer': 'Adicionar Camada',
    'layer.title': 'Camadas',
    'layer.name': 'Nome da Camada',
    'layer.thickness': 'Espessura (cm)',
    'layer.material': 'Material',
    'layer.remove': 'Remover',
    'layer.unit': 'm',
    'dimensions.length': 'Comprimento',
    'dimensions.width': 'Largura',
    'dimensions.height': 'Altura',
    'dimensions.lengthUnit': 'm',
    'dimensions.widthUnit': 'm',
    'dimensions.heightUnit': 'm',
    'results.area': 'Área Total',
    'results.volume': 'Volume Total',
    'results.linearMeters': 'Metros Lineares',
    'results.m2': 'm²',
    'results.m3': 'm³',
    'results.m': 'm',
    'results.summary': 'Resumo dos Resultados',
    'results.noData': 'Sem cálculos ainda. Adicione elementos para começar.',
    'material.name': 'Nome do Material',
    'material.pricePerUnit': 'Preço por Unidade',
    'material.unit': 'Unidade (m², m³, m)',
    'material.totalCost': 'Custo Total',
    'material.addMaterial': 'Adicionar Material',
    'material.summary': 'Resumo de Preços de Materiais',
    'element.name': 'Nome do Elemento',
    'element.dimensions': 'Dimensões',
    'element.quantity': 'Qtd',
    'element.type': 'Tipo',
    'element.breakdownTable': 'Detalhamento de Elementos',
    'element.noElements': 'Nenhum elemento adicionado ainda.',
    'export.title': 'Exportar Dados',
    'export.csv': 'Exportar como CSV',
    'export.excel': 'Exportar como Excel',
    'export.pdf': 'Exportar como PDF',
    'export.cancel': 'Cancelar',
    'export.download': 'Baixar',
    'actions.calculate': 'Calcular',
    'actions.reset': 'Redefinir',
    'actions.clear': 'Limpar Tudo',
    'actions.add': 'Adicionar',
    'actions.delete': 'Remover',
    'actions.edit': 'Editar',
    'actions.save': 'Salvar',
    'actions.cancel': 'Cancelar',
    'validation.required': 'Este campo é obrigatório',
    'validation.invalidNumber': 'Por favor, digite um número válido',
    'validation.positiveNumber': 'Por favor, digite um número positivo',
    'validation.invalidDimensions': 'Dimensões inválidas fornecidas',
  },
  ru: {
    'app.title': 'Калькулятор Объема',
    'app.subtitle': 'Профессиональная Оценка Объема и Строительных Материалов',
    'topbar.language': 'Язык',
    'topbar.settings': 'Настройки',
    'topbar.export': 'Экспорт',
    'layer.addLayer': 'Добавить Слой',
    'layer.title': 'Слои',
    'layer.name': 'Название Слоя',
    'layer.thickness': 'Толщина (см)',
    'layer.material': 'Материал',
    'layer.remove': 'Удалить',
    'layer.unit': 'м',
    'dimensions.length': 'Длина',
    'dimensions.width': 'Ширина',
    'dimensions.height': 'Высота',
    'dimensions.lengthUnit': 'м',
    'dimensions.widthUnit': 'м',
    'dimensions.heightUnit': 'м',
    'results.area': 'Общая Площадь',
    'results.volume': 'Общий Объем',
    'results.linearMeters': 'Погонные Метры',
    'results.m2': 'м²',
    'results.m3': 'м³',
    'results.m': 'м',
    'results.summary': 'Сводка Результатов',
    'results.noData': 'Расчетов еще нет. Добавьте элементы для начала.',
    'material.name': 'Название Материала',
    'material.pricePerUnit': 'Цена за Единицу',
    'material.unit': 'Единица (м², м³, м)',
    'material.totalCost': 'Общая Стоимость',
    'material.addMaterial': 'Добавить Материал',
    'material.summary': 'Сводка Цен на Материалы',
    'element.name': 'Название Элемента',
    'element.dimensions': 'Размеры',
    'element.quantity': 'Кол-во',
    'element.type': 'Тип',
    'element.breakdownTable': 'Разбор Элементов',
    'element.noElements': 'Элементы еще не добавлены.',
    'export.title': 'Экспорт Данных',
    'export.csv': 'Экспортировать как CSV',
    'export.excel': 'Экспортировать как Excel',
    'export.pdf': 'Экспортировать как PDF',
    'export.cancel': 'Отмена',
    'export.download': 'Загрузить',
    'actions.calculate': 'Рассчитать',
    'actions.reset': 'Сброс',
    'actions.clear': 'Очистить Все',
    'actions.add': 'Добавить',
    'actions.delete': 'Удалить',
    'actions.edit': 'Редактировать',
    'actions.save': 'Сохранить',
    'actions.cancel': 'Отмена',
    'validation.required': 'Это поле обязательно',
    'validation.invalidNumber': 'Пожалуйста, введите корректное число',
    'validation.positiveNumber': 'Пожалуйста, введите положительное число',
    'validation.invalidDimensions': 'Предоставлены неверные размеры',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language | null;
    if (saved && translations[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    if (translations[lang]) {
      setLanguageState(lang);
      localStorage.setItem('language', lang);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
